modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/FabricMC/fabric-example-mod"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="Me!"
description='''
This is an example description! Tell everyone what your mod is about!
'''
logoFile="assets/orebit/icon.png"

[[dependencies.${id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"
