modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/FabricMC/fabric-example-mod"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="Me!"
description='''
This is an example description! Tell everyone what your mod is about!
'''
logoFile="assets/orebit/icon.png"

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[21.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="architectury"
type="required"
versionRange="[15,)"
ordering="NONE"
side="BOTH"
